version: 0.0
os: linux
files:
  - source: /
    destination: /sentitext
hooks:
  AfterInstall:
    - location: scripts/install_app_dependencies.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 3600
      runas: root