version: 0.0
os: linux
files:
  - source: .
  destination: /sentitext
hooks:
  AfterInstall:
    - location: scripts/install_app_dependencies
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 120
      runas: root