version: 0.0
os: linux
files:
  - source: /
  destination: /sentitext
hooks:
  BeforeInstall:
    - location: scripts/install_app_dependencies.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root